### Spotify makes new songs recommendations to users every week based on the songs that are currently saved in their playlists. 

### Using the below dictionary which is a collection of playlists mantained by 'other' sample users, recommend songs to a new user. 

Using the below points as guidelines:
* Listing the songs currently listed by a new user. This can have entries like SONGID01,SONGID02,...
* Finding a playlist in the dictionary, where ALL of these songs are present (there can be more than 1 such playlist)
* From this playlist(s), pick the remaining songs and recommend to the new user (refer below examples for more details)

In [2]:
##importing all important package..
import pandas as pd
import numpy as np

In [3]:
# generates random playlist
import random,string
songids=['SONGID'+str(i).zfill(2) for i in range(1,21)]
userid=[''.join('USER')+str(random.randint(10,99)).zfill(2) for i in range(100)]
playlist={i:j for i,j in zip(userid,[random.sample(songids,random.randint(4,7)) for i in range(len(userid))])}
playlist

{'USER27': ['SONGID06',
  'SONGID04',
  'SONGID19',
  'SONGID12',
  'SONGID16',
  'SONGID13',
  'SONGID15'],
 'USER17': ['SONGID01',
  'SONGID04',
  'SONGID17',
  'SONGID06',
  'SONGID08',
  'SONGID19'],
 'USER58': ['SONGID16', 'SONGID18', 'SONGID02', 'SONGID12', 'SONGID05'],
 'USER66': ['SONGID03', 'SONGID09', 'SONGID11', 'SONGID19', 'SONGID02'],
 'USER96': ['SONGID15',
  'SONGID17',
  'SONGID14',
  'SONGID05',
  'SONGID04',
  'SONGID13',
  'SONGID12'],
 'USER89': ['SONGID17', 'SONGID04', 'SONGID19', 'SONGID12'],
 'USER77': ['SONGID14', 'SONGID02', 'SONGID05', 'SONGID12', 'SONGID07'],
 'USER97': ['SONGID01',
  'SONGID08',
  'SONGID05',
  'SONGID12',
  'SONGID20',
  'SONGID15'],
 'USER42': ['SONGID20',
  'SONGID03',
  'SONGID06',
  'SONGID04',
  'SONGID16',
  'SONGID02',
  'SONGID17'],
 'USER39': ['SONGID20', 'SONGID04', 'SONGID15', 'SONGID05', 'SONGID10'],
 'USER33': ['SONGID04', 'SONGID13', 'SONGID12', 'SONGID15'],
 'USER15': ['SONGID19', 'SONGID11', 'SONGID13', 'SONGID17'],
 'USER49': ['SONGID19',
  'SONGID17',
  'SONGID08',
  'SONGID11',
  'SONGID05',
  'SONGID02',
  'SONGID20'],
 'USER34': ['SONGID06', 'SONGID16', 'SONGID19', 'SONGID13', 'SONGID20'],
 'USER19': ['SONGID11',
  'SONGID16',
  'SONGID13',
  'SONGID14',
  'SONGID06',
  'SONGID07'],
 'USER25': ['SONGID20', 'SONGID19', 'SONGID13', 'SONGID16'],
 'USER78': ['SONGID13',
  'SONGID14',
  'SONGID01',
  'SONGID20',
  'SONGID09',
  'SONGID18',
  'SONGID08'],
 'USER88': ['SONGID11',
  'SONGID16',
  'SONGID14',
  'SONGID12',
  'SONGID10',
  'SONGID03',
  'SONGID08'],
 'USER68': ['SONGID04',
  'SONGID16',
  'SONGID12',
  'SONGID03',
  'SONGID13',
  'SONGID06'],
 'USER32': ['SONGID16',
  'SONGID11',
  'SONGID05',
  'SONGID17',
  'SONGID07',
  'SONGID14'],
 'USER29': ['SONGID01', 'SONGID11', 'SONGID14', 'SONGID09', 'SONGID16'],
 'USER47': ['SONGID02',
  'SONGID20',
  'SONGID04',
  'SONGID07',
  'SONGID05',
  'SONGID17'],
 'USER70': ['SONGID03', 'SONGID18', 'SONGID07', 'SONGID06', 'SONGID16'],
 'USER51': ['SONGID05',
  'SONGID15',
  'SONGID11',
  'SONGID07',
  'SONGID04',
  'SONGID01'],
 'USER24': ['SONGID15',
  'SONGID12',
  'SONGID07',
  'SONGID05',
  'SONGID14',
  'SONGID10'],
 'USER56': ['SONGID19',
  'SONGID11',
  'SONGID05',
  'SONGID08',
  'SONGID13',
  'SONGID12',
  'SONGID14'],
 'USER84': ['SONGID19', 'SONGID07', 'SONGID14', 'SONGID03'],
 'USER81': ['SONGID10', 'SONGID12', 'SONGID01', 'SONGID18', 'SONGID14'],
 'USER23': ['SONGID07',
  'SONGID16',
  'SONGID01',
  'SONGID10',
  'SONGID20',
  'SONGID09'],
 'USER52': ['SONGID14', 'SONGID06', 'SONGID20', 'SONGID15', 'SONGID01'],
 'USER82': ['SONGID01',
  'SONGID07',
  'SONGID11',
  'SONGID13',
  'SONGID19',
  'SONGID10',
  'SONGID02'],
 'USER69': ['SONGID05', 'SONGID07', 'SONGID18', 'SONGID17'],
 'USER43': ['SONGID13',
  'SONGID02',
  'SONGID14',
  'SONGID12',
  'SONGID10',
  'SONGID09',
  'SONGID06'],
 'USER36': ['SONGID05',
  'SONGID07',
  'SONGID20',
  'SONGID17',
  'SONGID02',
  'SONGID14',
  'SONGID09'],
 'USER22': ['SONGID14',
  'SONGID10',
  'SONGID02',
  'SONGID13',
  'SONGID08',
  'SONGID04'],
 'USER90': ['SONGID10',
  'SONGID20',
  'SONGID09',
  'SONGID01',
  'SONGID14',
  'SONGID13',
  'SONGID17'],
 'USER46': ['SONGID03',
  'SONGID17',
  'SONGID09',
  'SONGID14',
  'SONGID20',
  'SONGID02',
  'SONGID07'],
 'USER62': ['SONGID02',
  'SONGID05',
  'SONGID12',
  'SONGID06',
  'SONGID16',
  'SONGID19',
  'SONGID10'],
 'USER79': ['SONGID17', 'SONGID10', 'SONGID16', 'SONGID01', 'SONGID02'],
 'USER48': ['SONGID11', 'SONGID14', 'SONGID01', 'SONGID02'],
 'USER92': ['SONGID20', 'SONGID18', 'SONGID14', 'SONGID03', 'SONGID02'],
 'USER65': ['SONGID06', 'SONGID07', 'SONGID18', 'SONGID09'],
 'USER67': ['SONGID19',
  'SONGID09',
  'SONGID18',
  'SONGID02',
  'SONGID15',
  'SONGID20'],
 'USER40': ['SONGID01', 'SONGID08', 'SONGID05', 'SONGID19', 'SONGID17'],
 'USER64': ['SONGID17', 'SONGID10', 'SONGID02', 'SONGID15'],
 'USER94': ['SONGID08', 'SONGID12', 'SONGID11', 'SONGID13'],
 'USER71': ['SONGID18', 'SONGID03', 'SONGID13', 'SONGID10'],
 'USER86': ['SONGID19',
  'SONGID05',
  'SONGID20',
  'SONGID06',
  'SONGID07',
  'SONGID12'],
 'USER57': ['SONGID18',
  'SONGID16',
  'SONGID08',
  'SONGID04',
  'SONGID02',
  'SONGID20',
  'SONGID13'],
 'USER44': ['SONGID08', 'SONGID16', 'SONGID14', 'SONGID04'],
 'USER54': ['SONGID17',
  'SONGID05',
  'SONGID16',
  'SONGID08',
  'SONGID14',
  'SONGID11',
  'SONGID13'],
 'USER55': ['SONGID06', 'SONGID11', 'SONGID08', 'SONGID09'],
 'USER26': ['SONGID12',
  'SONGID17',
  'SONGID20',
  'SONGID04',
  'SONGID19',
  'SONGID18'],
 'USER11': ['SONGID18', 'SONGID17', 'SONGID08', 'SONGID16', 'SONGID13'],
 'USER16': ['SONGID12', 'SONGID15', 'SONGID16', 'SONGID09'],
 'USER45': ['SONGID06',
  'SONGID02',
  'SONGID15',
  'SONGID17',
  'SONGID11',
  'SONGID10',
  'SONGID16'],
 'USER41': ['SONGID10', 'SONGID17', 'SONGID14', 'SONGID16'],
 'USER76': ['SONGID13', 'SONGID05', 'SONGID08', 'SONGID15'],
 'USER28': ['SONGID15', 'SONGID06', 'SONGID05', 'SONGID01', 'SONGID16'],
 'USER20': ['SONGID02',
  'SONGID07',
  'SONGID09',
  'SONGID14',
  'SONGID12',
  'SONGID20',
  'SONGID18'],
 'USER99': ['SONGID09',
  'SONGID15',
  'SONGID10',
  'SONGID06',
  'SONGID03',
  'SONGID13',
  'SONGID07']}

In [4]:
df = pd.DataFrame.from_dict({k:pd.Series(v) for k,v in playlist.items()},orient='index')
df.head()

               0         1         2         3         4         5         6
USER27  SONGID06  SONGID04  SONGID19  SONGID12  SONGID16  SONGID13  SONGID15
USER17  SONGID01  SONGID04  SONGID17  SONGID06  SONGID08  SONGID19       NaN
USER58  SONGID16  SONGID18  SONGID02  SONGID12  SONGID05       NaN       NaN
USER66  SONGID03  SONGID09  SONGID11  SONGID19  SONGID02       NaN       NaN
USER96  SONGID15  SONGID17  SONGID14  SONGID05  SONGID04  SONGID13  SONGID12

In [5]:
#sorting the complete table index
df =df.sort_index()
df.head(5)

               0         1         2         3         4         5    6
USER11  SONGID18  SONGID17  SONGID08  SONGID16  SONGID13       NaN  NaN
USER15  SONGID19  SONGID11  SONGID13  SONGID17       NaN       NaN  NaN
USER16  SONGID12  SONGID15  SONGID16  SONGID09       NaN       NaN  NaN
USER17  SONGID01  SONGID04  SONGID17  SONGID06  SONGID08  SONGID19  NaN
USER19  SONGID11  SONGID16  SONGID13  SONGID14  SONGID06  SONGID07  NaN

In [6]:
df .info()

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, USER11 to USER99
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       61 non-null     object
 1   1       61 non-null     object
 2   2       61 non-null     object
 3   3       61 non-null     object
 4   4       45 non-null     object
 5   5       31 non-null     object
 6   6       18 non-null     object
dtypes: object(7)
memory usage: 3.8+ KB

In [7]:
#Let's say the new user has listened to these 3 songs  
new_list=['SONGID01','SONGID02','SONGID05']
new_list

['SONGID01', 'SONGID02', 'SONGID05']

create empty data frame
for loop to check whather the song exit in list
if all the dataframe of true and false 
if all the true fetch remainng song

In [11]:
for i in new_list:
    df1 = df.isin([i])
df1.head()

            0      1      2      3      4      5      6
USER11  False  False  False  False  False  False  False
USER15  False  False  False  False  False  False  False
USER16  False  False  False  False  False  False  False
USER17  False  False  False  False  False  False  False
USER19  False  False  False  False  False  False  False